[theme]
# Primary color for buttons, etc.
primaryColor = "mediumseagreen"

# Background color for the main content area
backgroundColor = "white"

# Background color for sidebar and header
secondaryBackgroundColor = "#EDF8F7"

# Color used for text
textColor = "darkgreen"

# Font style. Options are "sans serif", "serif", and "monospace"
font = "sans serif"